root = "."
tmp_dir = "tmp"

[build]
  cmd = "make build plugins"
  bin = "build/mindpalace"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", "build", "release"]
  exclude_file = ["events.json"]
  exclude_regex = [".*_templ\\.go"]
  delay = 1000
  stop_on_error = true
  send_interrupt = true
  kill_delay = 500

[log]
  time = true
  main_only = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
